### ISSUE TITLE
Use sources.list.d folder instead of appending to sources.list for apt repository

### ISSUE THREAD

**Issue by mtrp12** [VSCodium/vscodium.github.io#3]
In the vscodium website, the install command for ubuntu/debian adds the deb repo of vscodium to the sources.list. It would be better to use vscodium.list under /etc/sources.list.d as it would enable cleaner management of the repo. Adding to sources.list clutters the sources.list unnecessarily. It would be great if you changed it, as many people including me just copy paste the commands. Thank you.

**Comment by stripedpajamas** [comment]
@paulcarroty I don't have enough context to know if this makes sense to do -- can you weigh in here?

**Comment by PalinuroSec** [comment]
to put the repo in /etc/apt/sources.list.d/ is a good idea, but the pull request changes the wrong files: the build results of the jekyll build process.

let me pull the changes and move them to the proper files

**Comment by paulcarroty** [comment]
@stripedpajamas it just split the one configuration to many small `/etc/apt/sources.list.d/{app1.list,app2.list...}` files. The [docs](https://linux.die.net/man/5/sources.list) says:

`The package resource list is used to locate archives of the package distribution system in use on the system. This control file is located in /etc/apt/sources.list and *additionally* any files ending with ".list" in /etc/apt/sources.list.d are included.`

My opinion - this is just a waste of time because apt will use this sources in the same way.

**Comment by PalinuroSec** [comment]
website updated and readme file created to make the development and testing process easier
